package com.pseteamtwo.allways.data.question.source.network

import com.pseteamtwo.allways.data.question.QuestionType
import kotlinx.serialization.Serializable

/**
 * A question the user can fill in to provide information about himself.
 * This class is a representation of such question to be extracted from and saved to the
 * network database. It will be generated by according questionnaire repositories from JSON
 * from the network database.
 * As a question should be assigned to a user it will be stored to the local database with a
 * pseudonym which therefor is also a property of this class.
 *
 * @property id The unique identifier String of the question.
 * @property title The title of the question.
 * @property type The answer type [QuestionType] of the question.
 * @property options The options the user can choose from to answer the question.
 * (Ignored if [type] is [QuestionType.TEXT]).
 * @property answer The answer the user has given for the question.
 * @property pseudonym The pseudonym of the user which is used to store this question to the
 * network database.
 * @constructor Creates a question with the given properties.
 */
@Serializable
data class NetworkQuestion (
    val id: String,
    val title: String,
    val type: QuestionType,
    val options: List<String>? = null,
    val answer: String? = null,
    val pseudonym: String? = null,
)